version: '3.3'
services:
  dotnet:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ../
        target: /source
    tty: true
