FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl libunwind8 gettext apt-transport-https wget gpg software-properties-common git nano

# install dotnet-sdk-3.1.0
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb

RUN apt-get update
RUN add-apt-repository universe
RUN apt-get update
RUN apt-get install -y dotnet-sdk-3.1

# install dotnet-sdk-5.0
RUN wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y dotnet-sdk-5.0

# install dotnet-sdk-6.0
RUN apt-get update
RUN apt-get install -y dotnet-sdk-6.0

WORKDIR /source
